name: Go
on:
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
      
    - name: GolangCI-Lint Action
      uses: actions-contrib/golangci-lint@v0.1.0

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
        unzip sonar-scanner-cli-4.0.0.1744-linux.zip

    - name: Build
      run: |
        go test -short -coverprofile=coverage.out ./...
        golangci-lint run --disable=errcheck ./... > golangci.xml
        ./sonar-source -Dsonar.projectKey=test-app -Dsonar.source=. -Dsonar.host.url=http://64218f60.ngrok.io/webhooks -Dsonar.login=336865d5a0e971bd3266ee5e54fe109de500110c
