name: lint
on: [pull_request]
jobs:
  lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v1.0.3
